# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveapi', '0002_auto_20170520_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
